COLUMNNS:
  gender              :    object 
  ssc_percentage      :    float64
  ssc_board           :    object 
  hsc_percentage      :    float64
  hsc_board           :    object 
  hsc_subject         :    object 
  degree_percentage   :    float64
  undergrad_degree    :    object 
  work_experience     :    object 
  emp_test_percentage :    float64
  specialisation      :    object 
  mba_percent         :    float64
  status              :    object 

TARGET_COLUMN:  status

DROP_COLUMN:  UNNAMED :0

  