artifacts_root: artifacts

Data_Ingestion:
  dir: artifacts/data_ingestion
  url: https://github.com/arpanchakraborty23/data/raw/refs/heads/main/world_bank_dataset.zip
  local_dir: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/data

